### PR TITLE
use kube-env vars to check new/legacy stackdriver

### PR DESCRIPTION
**Pull request by garethbudden**
Hi @amanda-tarafa ,
This is essentially what we're currently doing at work to figure out if we're running in legacy or new version of stackdriver; it looks in `instance.attributes.kube-env` of the metadata json for the `HEAPSTER_USE_NEW_STACKDRIVER_RESOURCES` variable and uses the value found.
It does seem to work for us, but I appreciate you may not want to take a dependency like this into the library  as it looks like it's using internal operation details? #347

### CODE REVIEW

**Comment by jskeet** [comment]
I think we'd only want to rely on documented, stable environment variables. But Amanda can have a look in more detail on Monday - thanks for the PR.

**Comment by amanda-tarafa** [comment]
Hi @garethbudden, I'll check tomorrow how #347 is doing internally and get back to you on that.
I'll also try to find out if there is a more stable way to know whether we are running legacy or new Stackdriver, and maybe is just a matter of doing that. I'll update here as soon as I have more info.
Thanks for the PR.

**Comment by amanda-tarafa** [comment]
Just a heads up, I have asked internally and will update when we know more.
I will keep this PR open until we have come up with a plan. Thanks!

**Comment by amanda-tarafa** [comment]
Closing this PR now as we won't be supporting conditional detection of monitored resource types.
See [comment](https://github.com/googleapis/gax-dotnet/issues/347#issuecomment-586208127) in #347.
Please let us know if you encounter any problems with our approach and thanks very much for the PR.

**Pull request closed without merging**
