### PR TITLE
Date feedback

### PR DESCRIPTION
**Pull request by JasonMiggs**
Addressing feedback (so far) from Jon Skeet in https://github.com/googleapis/gax-dotnet

### CODE REVIEW

**Comment by jskeet** [comment]
Did you mean to close this PR? (Will have a look at it tomorrow assuming you didn't.)

**Comment by JasonMiggs** [comment]
Apologies, I meant to PR that into my company's forked repo's `master` branch. 😅

**Comment by jskeet** [comment]
Righto. If you make sure everything's where you expect it to be, I'll review tomorrow and hopefully we can get this in :)

**Comment by JasonMiggs** [comment]
Sounds good. It's currently in review internally right now, once approved it'll be appended to the existing PR: https://github.com/googleapis/gax-dotnet/pull/251

**Pull request closed without merging**
