### PR TITLE
Update to xunit v2.3.1 and Microsoft.NET.Test.Sdk v15.8.0

### PR DESCRIPTION
**Pull request by GR3G0R**
This is a follow up to #259 we will be submitting the Google.type.money PR once this is merged.

### CODE REVIEW

**Comment by jskeet** [comment]
I believe the commits aren't from one of the accounts registered in the CLA. You could either address this, or we could just treat this as a request to update our dependencies, and do it in a separate PR. (We'd probably do it for our other repos at the same time.)

Any thoughts?

**Comment by nycdotnet** [comment]
We are working on getting @gr3g0r on the CLA.  Should be presently.  Thank you.

**Comment by GR3G0R** [comment]
@jskeet, I believe the CLA for this the PR has been completed. Please let us know if you have need of additional support from our end. Thank you!

**Comment by jskeet** [comment]
All looks good; will check it in the morning (UK time) and merge unless I spot any other issues.

**Comment by GR3G0R** [comment]
Thanks @jskeet!

**Pull request merged**
