### PR TITLE
Release Google.Api.Gax version 3.7.0

### PR DESCRIPTION
**Pull request by jskeet**
No changes since 3.7.0-beta01

Changes since 3.6.0:

- Addition of RoutingHeaderExtractor and corresponding ApiCall methods to use it

### CODE REVIEW

**Review by amanda-tarafa — APPROVED** [review]
LGTM

**Comment by jskeet** [comment]
Closing for now as we need to investigate streaming first.

**Review by viacheslav-rostovtsev — APPROVED** [review]
LGTM

**Comment by jskeet** [comment]
Thanks - will release on Monday.

**Pull request merged**
